# KeyAll Plugin konfiguráció
# Az intervallum másodpercben (3600 = 1 óra)
interval: 3600

# A crate kulcs típusa (/pcrate giveKey <type> <player> 1)
key-type: example1

# Üzenetek
messages:
  broadcast-key: "&6&l[KeyAll] &eMindenki kapott egy &6Common &elada kulcsot! &a✔"
  keyall-started: "&6&l[KeyAll] &eAz automatikus kulcsosztás &aelindult&e!"
  keyall-stopped: "&6&l[KeyAll] &eAz automatikus kulcsosztás &cleallittatott&e."
  keyall-now: "&6&l[KeyAll] &eAzonnali kulcsosztás! Mindenki kap egy kulcsot!"
